spring:
  application:
    name: event-service # Имя сервиса, которое будет зарегистрировано в Eureka
  datasource:
    url: jdbc:postgresql://localhost:5432/qonaqzhai_events # Пример URL для PostgreSQL
    username: your_db_username
    password: your_db_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Автоматическое создание/обновление таблиц
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: never # Не запускать автоматическую инициализацию схемы при старте

server:
  port: 8082 # Порт, на котором будет работать сервис (рекомендуется выбрать уникальный)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Адрес Eureka сервера
  instance:
    hostname: localhost

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    kz.qonaqzhai: DEBUG